version: 2.1
jobs:
  build:
    docker:
      - image: billryan/gitbook
    steps:
      - checkout
      - restore_cache:
          keys:
            - "gitbook-plugins"
      - run:
          name: Install gitbook plugins
          command: gitbook install
      - run:
          name: Build website with gitbook
          command: gitbook init && gitbook build
      - save_cache:
          paths:
            - node_modules
          key: gitbook-plugins
      - persist_to_workspace:
          root: .
          paths:
            - _book
  deploy:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - attach_workspace:
          at: _book
      - add_ssh_keys:
          fingerprints:
            - "d0:70:ec:0d:01:57:e6:ff:f6:ce:9e:17:34:98:72:45"
      - run:
          name: Deploy to GitHub Pages
          command: sudo chmod +x deploy.sh && ./deploy.sh
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
