Version = "0.8.3"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-28"
Prologue = ""
Items = [
    "(0.8.2) 实参标准化选项全新改版，支持更多自定义维度",
    "修复了参数合并叠加后数值异常的 bug",
]
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/ace/opensvip_plugin_ace_0.8.3.zip"
