Version = "0.0.1"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-07-05"
Prologue = "首次发布"
Items = [

]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/lrc/opensvip_plugin_lrc_0.0.1.zip"
