Version = "1.7.0"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-06-24"
Prologue = ""
Items = [
    "注意：此版本需要框架版本为1.3.0及以上才能正常使用。请在 OpenSVIP 转换器顶部的菜单栏>帮助>关于 OpenSVIP 查看是否满足条件，如果不满足，请更新转换器",
    "改用 OpenSVIP 框架的汉字转拼音方案，新增“使用旧版的汉字转拼音方案”的选项，以便在两种汉字转拼音方案之间切换",
    "修复“仅拼音”下丢弃转音符号的错误",
]
Epilogue = ""
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_plugin_gjgj_1.7.0.zip"
