Version = "0.7.1"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-07-11"
Prologue = ""
Items = [
    "修复特定情况下曲速转换错误的问题",
]
Epilogue = ""
DownloadLink = "https://openvpi.github.io/downloads/opensvip_plugin_midi_0.7.1.zip"
