Version = "1.7.3"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-21"
Prologue = ""
Items = [
    "新增导入歌叽歌叽工程时移除歌词中的空白字符",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/gj/opensvip_plugin_gjgj_1.7.3.zip"
