Version = "1.8.4"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-07-25"
Prologue = ""
Items = [
    "修复了部分 svp 工程存在数值为 0 的参数点导致反序列化时数据格式转换失败的 bug",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/svp/opensvip_plugin_synthv_1.8.4.zip"
