Version = "1.2.0"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-08-10"
Prologue = ""
Items = [
    "支持设定 X Studio 安装路径或动态链接库存放路径",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/svip/opensvip_plugin_binsvip_1.2.0.zip"
