Version = "0.6.1"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-21"
Prologue = ""
Items = [
    "添加“保留全部发音信息”选项，用于控制是否保留 .acep 文件中冗余的发音信息",
    "修复少数情况下文件解码失败的 bug",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/ace/opensvip_plugin_ace_0.6.1.zip"
