Version = "0.7.0"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-06-19"
Prologue = ""
Items = [
    "新增多通道导入选项。对于一条轨道内有多个不同通道音符的情况，可以选择仅导入首条通道、全部拆分为轨道和自定义导入范围。",
    "半元音前移量的选项升级为拖拍前移补偿量，生效范围扩展到y-、w-、a-、o- 和 e-。",
    "调整了部分文案。",
]
Epilogue = ""
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_plugin_midi_0.7.0.zip"
