Version = "1.8.3"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-06-21"
Prologue = ""
Items = [
    "修复了部分 svp 工程存在负坐标音符导致转换失败的 bug",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/svp/opensvip_plugin_synthv_1.8.3.zip"
