Version = "0.7.1"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-24"
Prologue = ""
Items = [
    "修复了当音符靠近第一小节开头时可能转换失败的 bug",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/ace/opensvip_plugin_ace_0.7.1.zip"
