Version = "1.0.0"
RequiredFrameworkVersion = 1.0.0
Date = "2022-05-06"
Prologue = "随转换器公测发布"
Items = [
    
]
Epilogue = ""
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_plugin_jsonsvip_1.0.0.zip"
