Version = "0.8.0"
RequiredFrameworkVersion = "1.3.0"
Date = "2023-02-20"
Prologue = ""
Items = [
    "支持导出性别参数"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/diffsinger/opensvip_plugin_diffsinger_0.8.0.zip"
