Version = "0.8.3"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-08-22"
Prologue = ""
Items = [
    "修复导入曲速为120的文件时曲速丢失的问题"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/midi/opensvip_plugin_midi_0.8.3.zip"
