Version = "0.4.1"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-12-15"
Prologue = ""
Items = [
    "1. 优化分段策略，新增分段长度选项",
    "2. 优化尾部SP",
    "3. 默认使用严式词典"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/diffsinger/opensvip_plugin_diffsinger_0.4.1.zip"
