Version = "0.7.0"
RequiredFrameworkVersion = "1.3.0"
Date = "2023-02-05"
Prologue = ""
Items = [
    "新增 opencpop-extension 词典并作为默认值，支持若干非标准发音",
    "发音不在所选词典内时，将提示用户检查发音或更换词典",
    "移除音高和音素选项，默认有参"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/diffsinger/opensvip_plugin_diffsinger_0.7.0.zip"
