Version = "1.3.0"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-12-17"
Prologue = ""
Items = [
    "支持无依赖式读取和写入，开启后无需安装 X Studio 即可转换",
]
Epilogue = "本次更新贡献者：至精至简"
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/svip/opensvip_plugin_binsvip_1.3.0.zip"
