Version = "0.6.0"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-21"
Prologue = ""
Items = [
    "支持作为输入端（但暂不支持转换伴奏偏移和除音高外的其他参数）",
    "由于 ACE Studio 已修复相关 bug，因此移除了 “转换伴奏信息” 的输出选项",
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/ace/opensvip_plugin_ace_0.6.0.zip"
