Version = "0.4.1"
RequiredFrameworkVersion = "1.3.0"
Date = "2023-01-07"
Prologue = ""
Items = [
    "1. 默认选择音素和音高有参",
    "2. 音素或音高无参时，将提示用户冻结参数"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/diffsinger/opensvip_plugin_diffsinger_0.5.0.zip"
