Version = "0.8.1"
RequiredFrameworkVersion = "1.3.0"
Date = "2022-07-29"
Prologue = ""
Items = [
    "导入出现错误时引导用户选择忽略错误"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/midi/opensvip_plugin_midi_0.8.1.zip"
