Version = "1.0.0"
RequiredFrameworkVersion = "1.0.0"
Date = "2022-05-06"
Prologue = "随转换器公测发布"
Items = [
    
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/json/opensvip_plugin_jsonsvip_1.0.0.zip"
