Version = "0.6.0"
RequiredFrameworkVersion = "1.3.0"
Date = "2023-01-15"
Prologue = ""
Items = [
    "1. 优化呼吸声策略",
    "2. 优化分段阈值",
    "3. 新增分段音符间隔选项"
]
Epilogue = ""
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/plugins/diffsinger/opensvip_plugin_diffsinger_0.6.0.zip"
