Version = "1.4.0"
Date = "2022-06-27"
Prologue = "此版本引入了插件检查更新与一键升级机制。若要更新某个已安装的插件，请遵循以下步骤："
Items = [
    "在“导入工程格式”或“导出工程格式”下拉选项框中选择对应的插件；",
    "点击右侧“查看详细信息”按钮，打开详细信息面板；",
    "若检测到该插件更新，在“版本号”右侧会出现“获取更新”按钮；",
    "单击“获取更新”，在随后弹出的更新日志对话框中点击“更新”；",
    "此时新版本插件会在后台进行下载，随后将提示进行安装，根据指引完成即可。",
]
Epilogue = "部分插件可能需要先将转换器升级至较新的版本才会推送更新。若您怀疑网络原因导致无法正常获取更新，请尝试多次切换导入/导出插件，或使用菜单栏“关于-检查更新”测试能否正常连通更新服务。若无法连通，请通过版本仓库手动下载更新。\n欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_converter_1.4.0.zip"
