Version = "1.2.3"
Date = "2022-06-09"
Prologue = "此版本包含插件兼容性改进和错误修复，建议所有用户更新。"
Items = [
    "新增插件兼容性检查，试图安装不兼容当前版本的插件时会提示更新应用",
    "延长了高级选项 Tips 的停留时间，阅读更友好",
    "框架依赖更新：修复了 SynthV 插件导入音高时出错的 bug",
]
Epilogue = "欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_converter_1.2.3.zip"
