Version = "1.2.0"
Date = "2022-05-05"
Prologue = "面向未来的歌声合成工程转换器：OpenSVIP 正式开启公测！相比于最后一个预览版本，本次更新内容如下："
Items = [
    "新增了启动时检查更新的选项，默认为开启",
    "当插件文件夹冲突时，提供强制覆盖安装的选项（而非报错并拒绝安装）",
]
Epilogue = "感谢各位团队成员为项目作出的贡献！"
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_converter_1.2.0.zip"
