Version = "1.2.2"
Date = "2022-05-25"
Prologue = "此版本包含重要的错误修复，建议所有用户更新。"
Items = [
    "优化插件信息排版和其他一些 UI 细节逻辑",
    "添加新用户引导功能，在首次进入时引导用户下载并安装插件，同时禁用大部分菜单项以防止误操作",
    "修复了转换任务运行时点击强制退出应用却不起效果的 bug",
    "【框架依赖更新】修复了部分插件参数曲线编辑范围计算的 bug",
    "【框架依赖更新】修复了极少数情况下 SynthV 插件需要极长的时间才能解析一个工程文件的 bug",
]
Epilogue = "欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_converter_1.2.2.zip"
