Version = "1.4.1"
Date = "2022-07-14"
Prologue = "注意：转换器官网网址已更换。需要更新此版本后才可接收后续的转换器和插件更新。"
Items = [
]
Epilogue = "欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/converter/opensvip_converter_1.4.1.zip"
