Version = "1.5.0"
Date = "2023-02-22"
Prologue = "此版本包含功能更新。"
Items = [
    "新增插件更新 toast 通知提醒"
]
Epilogue = "欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi-1307911855.cos.ap-beijing.myqcloud.com/converter/opensvip_converter_1.5.0.zip"
