Version = "1.3.0"
Date = "2022-06-21"
Prologue = ""
Items = [
    "支持多线程加速转换，充分利用性能（可以在“设置”菜单栏中关闭）",
    "为所有的插件引入了统一高效的汉字转拼音接口，各插件适配更新后可提高拼音转换的准确度并修复一些错误",
]
Epilogue = "欢迎加入转换器反馈交流 QQ 群：687772360"
DownloadLink = "https://openvpi.github.io/home/downloads/opensvip_converter_1.3.0.zip"
